sudo: true
language: node_js
node_js:
- 8.0.0
- 7.8.0
- 6.9.1
cache:
  yarn: true
before_install:
- chmod +x ./.travis/*.sh
- "./.travis/validate_last_commit_message.sh"
- npm run tools
install:
- yarn install
script:
- echo "Running tests against $(node -v) ..."
- yarn run validate
jobs:
  include:
  - stage: release
    node_js: 6.9.1
    script:
    - echo "Deploying to npm ..."
    - "./.travis/publish.sh"
branches:
  only:
  - master
env:
  global:
  - secure: WknTsh6r9e8B8C24yzYgIixav/BMevIRb/GEtn8WSC5ovlnaWDaXqEdWg8gpi/2wBQQYwQWkG8D2x1OhSUiQkv3qaYr8tWHKd0Xlk17gbv8Nc7F2Ynwfhl9Zgf7nYU4DTqiUpggV8ejCHq+k0UGoKsPFh1RucgBqzwB5dhVZKsYo5Pgg9QlWBSmc9XQ1yMOyUiiOwI1aC8t7hUulynQNCFzKi/Ac++S4qnPIMcCQENOph8+K+iGCxbJZ0fPZgIFHp2fEpU5iP92TZuJOuopitwcGI8gh3YEHg7CaxoCKB4TivQZLN9OSg6wKmFDu2IQXgy/hrVQi7hJNCyEX6A394Chzh3oSThvS2j+yaxuh4yNclOaTHYwn9RRU8wv+rPJbqI2KvhWu2KJydHMm94kGGqECifGapgaNb3z3cCeQ7wUs0vyNsM3JW9PWwkMjcjgZG8Qnf/x4McryV8Vyv82nWwwFAvVjprKkrCbKyY398M48/z5fuCcNCohj2B3DF5ijY5lR7fC60Vomg68cy6xHYUDCdjIKguddNxRq9xcOqzNv9VI9N8N8UYcsptRzwNZwO+fF6nUTy3gxGrIHqun/zCHFxGS/VNUNnONhcWTCH/WSEGHosfjx+JsLEOrFB0NGtL78XHiqPC9G8NXw8a3U6/KMMdifDwEGkhd9qdmf4/U=
  - secure: hkry1ru1k8+LdqX0nqqjwLzRknFnI0jDoj0duGmNN/ht7rajoGJEOMSFnZMSXcQkUHQj2qVEwsDnYHUTJTzHXc+s4eJD0ibjGhKKvQMlnAQIb6bl/R54kFgHUdLmE/3NZSJWJk7BujV/8fPn7SVczz9EJ69XpO79zQBM+Fk3eiH57t0OzkG+72VP26rfzDgkuwqzUX56hQg3ruFhsHtbQhsmB+QWmRvDyhBU78hTUWRx6Qh8yvUoip8pPB8/CzP8UVEOY2z/djkkTsPqd1bR5QdQ5FElZEn0Y9S/+Cq+WJCaBd9jkQX4QPAcj997T1RxG2J9yLD4ws9WZMyXFvZKBZsr33s+Wvxnizkuy05gcSBiPuSgsKjlpt0PGPl0xYDlt/NqbvpTlDHKBNwkCkPrtAeY1V4ZArFWJIehaWjqnZ7CPAhk6fbVtx3GVkf2FrUdMXd/GbccgRD6pEnkgKavnOttXEOj+Fxxg4kuotIlsjdsbMBYg2/tSf89DxxxK3SYFW6iKQjg3UpgwVaz6dOaPTUs720tfSJ+zZ51efUBxwEDIQeWE+68VhviExfAotg7y7tL2jIu1VoL202Ij5HbWet+3Im6Yl9DzRUeJuUPBklKFEislzRc6+820lS+hComXL7GCyjaEXHvX8hd4wj3mgZpOvL0kaHQViALytsW8qE=
